#
# nim thisFileName
#
#  Input:   ../../src/libc/fonticon/IconsFontAwesome6.h
#  Oputput: src/iconFontsTblDef.zig
#

const cFontHeader = "../../src/libc/fonticon/IconsFontAwesome6.h"

import strutils,strformat,pegs
#var fontsTbl{.global.} = [ (ICON_FA_NNN, "ICON_FA_NNN"), (ICON_FA_NNN1, "ICON_FA_NNN1", ... ]

const sHeader = """
// DON'T EDIT THIS FILE
// This file is auto generated by "nim makeIconFontsTblDef.nims"

const fnt = @import ("appimgui").ifa;
"""
var sOut = sHeader

sOut.add "\npub const iconFontsTbl = [_][*c]const u8{\n"
for line in readfile(cFontHeader).split('\n'):
  if line =~ peg"@'ICON_FA_'":
    let name = line.strip.split(' ')[1]
    sOut.add fmt"  fnt.{name} ++ "" {name}"" ," & "\n"

sOut.add "};"

#writefile("src/iconFontsTblDef.zig",sOut)

sOut.add "\n\n\n"

sOut.add "\npub const iconFontsTbl2 = [_][2][*c]const u8{\n"
for line in readfile(cFontHeader).split('\n'):
  if line =~ peg"@'ICON_FA_'":
    let name = line.strip.split(' ')[1]
    sOut.add fmt" [2][*c]const u8{{fnt.{name}, "" {name}""  }}," & "\n"

sOut.add "};"

writefile("src/iconFontsTblDef.zig",sOut)


# pub const iconFontsTbl2: [3][2][*c]const u8 = [3][2][*c]const u8{
#   [2][*c]const u8{fnt.ICON_FA_0 ,  " ICON_FA_0"},
#   [2][*c]const u8{fnt.ICON_FA_1 ,  " ICON_FA_1"},
#   [2][*c]const u8{fnt.ICON_FA_2 ,  " ICON_FA_2"},
# };
