DIRS = \
	appimgui \
	dcimgui \
	fonticon \
	glfw \
	imcolortextedit \
	imfileopendialog \
	imguizmo\
	imguizoomableimage \
	imknobs\
	imnodes\
	implot\
	implot3d\
	impl_glfw \
	impl_opengl3 \
	impl_sdlgpu3 \
	impl_win32 \
	imspinner \
	imtoggle \
	loadicon \
	loadimage \
	loadimage_sdlgpu3 \
	raylib \
	rlimgui \
	saveimage \
	setupfont \
	utils \
	zoomglass

all:
	clear
	$(foreach exdir,$(DIRS), $(call def_make,$(exdir),$@))

clean:
	$(foreach exdir,$(DIRS), $(call def_make,$(exdir),$@))

fmt:
	$(foreach exdir,$(DIRS), $(call def_make,$(exdir),$@))

gen:
	@-$(foreach exdir,$(DIRS), $(call def_make,$(exdir),$@))


#
define def_make
	@echo ==== Enter: $(1) ====
	@-$(MAKE) -C  $(1) $(2)

endef

MAKEFLAGS += --no-print-directory
